### ISSUE TITLE
use standard PDLIBBUILDER_DIR variable

### ISSUE THREAD

**Issue by umlaeute** [electrickery/pd-windowing#1]
to allow overriding the used Makefile.pdlibbuilder with a system-specific (or updated) one.

See https://github.com/pure-data/pd-lib-builder/blob/master/tips-tricks.md#project-management for a rationale.

(it greatly helps with using a modern pd-lib-builder in a uniform way)

**Comment by electrickery** [comment]
Is it correct to assume this should be done for all my pd-* repositories, not just pd_windowing?

**Comment by umlaeute** [comment]
yes :-)

**Comment by electrickery** [comment]
Fixed this too for al my pd-related repositories.

**Comment by umlaeute** [comment]
closing this as completed.
